### ISSUE TITLE
Make plugins import and implement the UriResolver interface

### ISSUE THREAD

**Issue by namesty** [polywrap/rust-client#28]
Currently resolver plugins don't import/implement the UriResolver interface like the Typescript client plugins do. The resolver realted methods are just declared by hand currently. This is because interface functionality wasn't enabled at the time the plugins were created.

They need to import and implement the interface.

**Comment by cbrzn** [comment]
this will be closed because we're going to use the wrapper resolvers (https://github.com/polywrap/uri-resolver-extensions) and just need the plugins
